theme: jekyll-theme-cayman
title: "Considering the Ethical Implications of Autonomous Vehicles in Society"
description: "CS 4001 Final Project, Summer 2020 @ Georgia Tech"
description: "By: Zack Vogel"
