theme: jekyll-theme-cayman
title: "Considering the Ethical Implications of Autonomous Vehicles in Society"
description: "Submitted by Zack Vogel in partial fulfillment of CS 4001 @ Georgia Tech, Summer 2020"
